version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
      - "8080:8080"  # if using WebSocket
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /dev/ttyS3:/dev/ttyS3  # only on Linux
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3307
      DB_USER: root
      DB_PASSWORD: nctladnun
    

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nctladnun
      MYSQL_DATABASE: hopito_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
